# Please check this page for details. 
# https://github.com/Team-Fruit/SignPictureManager/wiki/Config
# Do not change config-version.
config-version: 1
limits:
  offset: 0
  size: 0
dimBlacklist: []
replaceSignText: true
lang: en_us
