name: SignPictureManager
main: net.teamfruit.signpic.manager.SignPictureManager
version: 1.0.0.beta
author: TeamFruit
database: true
commands:
  signpicturemanager:
    description: SignPictureManagerCommand.
    usage: /<command> <subcommand>
    permission-message: You don't have <permission>
    aliases:
      - signpicmanager
      - sm
permissions:
  signpic.*:
    description: Full permission of SignPictureManager.
    default: false
    children:
      signpic.place.*: true
      signpic.command.*: true
      signpic.manage.*: true
  signpic.place:
    description: Place SignPicture.
    default: true
  signpic.place.*:
    description: Permission to place SignPicture with all attributes.
    default: true
    children:
      signpic.place: true
      signpic.place.offset: true
      signpic.place.animation: true
      signpic.place.rotation: true
      signpic.place.gif: true
  signpic.place.offset:
    description: Allow placing of SignPicture with offset attribute.
    default: true
  signpic.place.animation:
    description: Allow placing of SignPicture with animation attribute.
    default: true
  signpic.place.rotation:
    description: Allow placing of SignPicture with animation attribute.
    default: true
  signpic.place.gif:
    description: Allow to place SignPicture of Gif image.
    default: true
  signpic.manage.*:
    description: Permission to operate SignPicture.
    default: op
    children:
      signpic.manage.open: true
      signpic.manage.scan: true
      signpic.manage.reload: true
      signpic.manage.edit: true
      signpic.manage.remove: true
  signpic.manage.open:
    description: Command to open client's Gui.
    default: op
  signpic.manage.scan:
    description: Permission to execute all scan commands.
    default: false
  signpic.manage.reload:
    description: Reload SignPictureManager.
    default: false
  signpic.manage.edit:
    description: Permission to rewrite SignPicture.
    default: op
  signpic.manage.remove:
    description: Permission to destroy SignPicture.
    default: op
